### ISSUE TITLE
Missing required architecture arm64 

### ISSUE THREAD

**Issue by Talgat777** [flurry/flutter-flurry-sdk#3]
Can't compile the project for IOS after importing this SDK. Error:

Command CompileSwiftSources failed with a nonzero exit code
    ld: warning: ignoring file /Users/***/Documents/Repo/***/build/ios/Debug-iphonesimulator/Flurry-iOS-SDK/Flurry_iOS_SDK.framework/Flurry_iOS_SDK, missing required architecture arm64 in file /Users/***/Documents/Repo/***/build/ios/Debug-iphonesimulator/Flurry-iOS-SDK/Flurry_iOS_SDK.framework/Flurry_iOS_SDK (2 slices)
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_FlurryParamBuilder", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FlurryCCPA", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FlurryUserProperties", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_Flurry", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
         (maybe you meant: _OBJC_CLASS_$_FlurryFlutterPlugin)
      "_OBJC_CLASS_$_FlurrySessionBuilder", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FConfig", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
      "_OBJC_CLASS_$_FlurryMessaging", referenced from:
          objc-class-ref in FlurryFlutterPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hantao-flurrydev** [comment]
Could you try exclude arm64 arch on App level in XCode project? as currently we are excluding arm64 for iOS simulator on sdk level.

**Comment by FlurryDevNP** [comment]
Here are the build settings for excluded architecture
![Screen Shot 2022-02-01 at 10 45 46 AM](https://user-images.githubusercontent.com/60984913/152033798-e58028e0-a366-4296-849e-04bdaf7d3954.png)

**Comment by jodymac** [comment]
Will the simulator be supported in the future?  I can build to my device, but prefer to work in the simulator for the majority of the time and convenience

**Comment by blazer82** [comment]
Is there a workaround to keep working with the simulator or do we need to exclude the flurry dependency entirely on the simulator?

**Comment by FlurryDevNP** [comment]
Hello @jodymac and @blazer82 , you can try building the app on simulators with x86_64 architecture instead of arm64.

**Comment by blazer82** [comment]
@FlurryDevNP thanks for the suggestion. It did not work for me (or I did it wrong). Why do you need to exclude simulators anyway? I wouldn't even care if the library was disabled on simulators if it at least builds. Right now I need to maintain two branches of my code base - one with the flurry dependency in it and one without it - which isn't really sustainable in the long run.

**Comment by hantao-flurrydev** [comment]
@blazer82 This procedure is an accommodation for how our native iOS SDK's set up. Since M1 machine brings new simulator slice (arm64) so does XCode >=12 available archs, our iOS SDK is excluding arm64 in podspec settings in order for non M1 machine to build on simulators (simulators can still run on x86_64). So this might require users to exclude arm64 for `simulator` in the build settings, because by default it is available archs on xcode >=12.

**Comment by jodymac** [comment]
I was unable to get your suggestion to work as well.  I was a version behind, so I upgraded to the latest.  Same result.  I'm on Intel, macos Big sur 11.6.3, xcode 13.2.1.  Perhaps more detailed instructions as even your screenshots didn't match mine.  I can deal with having to run it on my device to test, but I don't want to have a second Flurry disabled branch/flavor solely just to be able to build and test all the other aspects of the app.  I use the simulator quite frequently and test multiple screen sizes before uploading to testflight.

**Comment by hantao-flurrydev** [comment]
@jodymac @blazer82 sorry for this issue. I was testing this and found the `arm64` should be excluded for pods target as well. The built framework skipped our native sdk excluded archs, so that have to do it manually on non M1 machine
<img width="1001" alt="Screen Shot 2022-02-16 at 10 47 25 AM" src="https://user-images.githubusercontent.com/55259334/154335186-e0957bf3-9e87-48e0-b5a8-e3fa75b55df0.png">
<img width="976" alt="Screen Shot 2022-02-16 at 10 47 36 AM" src="https://user-images.githubusercontent.com/55259334/154335209-15745c14-8eff-45dc-8924-812b11a68dfe.png">
<img width="995" alt="Screen Shot 2022-02-16 at 10 47 44 AM" src="https://user-images.githubusercontent.com/55259334/154335230-e20258a4-b20e-4b7e-9da4-675882c6d036.png">
<img width="957" alt="Screen Shot 2022-02-16 at 10 47 51 AM" src="https://user-images.githubusercontent.com/55259334/154335247-08abfabc-e60b-4b28-bd1e-e290155dbf11.png">
.

**Comment by blazer82** [comment]
@hantao-flurrydev thank you! This seems to work when starting the app in Xcode. Somehow the changes on the `flutter_flurry_sdk` target seem to get lost when executing `flutter run` however. Any idea what might be the cause for this?

**Comment by blazer82** [comment]
@hantao-flurrydev @Talgat777 @jodymac I could fix the issue by following the steps above and manually editing the file `flutter_flurry_sdk.podspec.json` inside the `flutter_flurry_sdk`. I also created a PR to hopefully fix this permanently.

I just changed

    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "i386"


to

    "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "i386 arm64"

**Comment by jodymac** [comment]
Thanks everybody! The above workarounds have me working like I desired.  Hassle free.
